=== pma93/ServiciosSoftware/segurosdomain/src/main/resources/SegurosDomain.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.unican.es/ss/SegurosDomain"
	xmlns:tns="http://www.unican.es/ss/SegurosDomain"
	elementFormDefault="qualified">

	<element name="aseguradora">
		<complexType>
			<sequence>
				<element name="cliente" type="tns:Cliente" minOccurs="0"
					maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>

	<complexType name="Cliente">
		<sequence>
			<element name="nombre" type="string"/>
			<element name="email" type="tns:Email"/>
			<element name="seguro" type="tns:Seguro" minOccurs="1" maxOccurs="unbounded"/>
			<element name="parte" type="tns:Parte" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="dni" type="tns:DNI"/>
	</complexType>

	<simpleType name="DNI">
		<restriction base="string">
			<pattern value="[0-9]{8}[A-Z]"/>
		</restriction>
	</simpleType>

	<simpleType name="Email">
		<restriction base="string">
			<pattern value=".+\@.+\..+"/>
		</restriction>
	</simpleType>

	<simpleType name="SeguroID">
		<restriction base="string">
			<pattern value="[A-Z]{3}-[0-9]{6}"/>
		</restriction>
	</simpleType>

	<simpleType name="SeguroTipo">
		<restriction base="string">
			<enumeration value="TERCEROS" />
			<enumeration value="TODO_RIESGO" />
			<enumeration value="TODO_RIESGO_FRANQUICIA" />
		</restriction>
	</simpleType>

	<complexType name="Vehiculo">
		<sequence>
			<element name="potencia" type="integer"/>
			<element name="usoprofesional" type="boolean"/>
		</sequence>
		<attribute name="matricula" type="tns:VehiculoMatricula"/>
	</complexType>
	
	<simpleType name="VehiculoMatricula">
		<restriction base="string">
			<pattern value="[0-9]{4} [A-Z]{3}"/>
		</restriction>
	</simpleType>

	<complexType name="Seguro">
		<sequence>
			<element name="tipo" type="tns:SeguroTipo" />
			<element name="vehiculo" type="tns:Vehiculo" minOccurs="1" maxOccurs="unbounded" />
		</sequence>
		<attribute name="id" type="ID"/>
	</complexType>

	<complexType name="Parte">
		<sequence>
			<element name="importe" type="decimal" />
			<element name="fecha" type="string"/>
			<element name="seguroref" type="IDREF" />
		</sequence>
		<attribute name="id" type="tns:SeguroID"/>
	</complexType>
</schema>

=== pma93/ServiciosSoftware/segurosdomain/src/main/resources/SegurosDomain.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:aseguradora
	xmlns:tns="http://www.unican.es/ss/SegurosDomain"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.unican.es/ss/SegurosDomain SegurosDomain.xsd ">

	<tns:cliente dni="72391113E">
		<tns:nombre>Fernando Martínez</tns:nombre>
		<tns:email>fmartinez@unican.es</tns:email>
		<tns:seguro id="ABC-123456">
			<tns:tipo>TERCEROS</tns:tipo>
			<tns:vehiculo matricula="3467 KIO">
				<tns:potencia>100</tns:potencia>
				<tns:usoprofesional>false</tns:usoprofesional>
			</tns:vehiculo>
		</tns:seguro>
		<tns:seguro id="DEF-123456">
			<tns:tipo>TODO_RIESGO</tns:tipo>
			<tns:vehiculo matricula="3461 AZE">
				<tns:potencia>240</tns:potencia>
				<tns:usoprofesional>true</tns:usoprofesional>
			</tns:vehiculo>
		</tns:seguro>
		<tns:seguro id="FGH-123456">
			<tns:tipo>TODO_RIESGO</tns:tipo>
			<tns:vehiculo matricula="3462 PAU">
				<tns:potencia>150</tns:potencia>
				<tns:usoprofesional>false</tns:usoprofesional>
			</tns:vehiculo>
		</tns:seguro>
		<tns:parte>
			<tns:importe>112.0</tns:importe>
			<tns:fecha>2019-02-05+12:14</tns:fecha>
			<tns:seguro>FGH-123456</tns:seguro>
		</tns:parte>
	</tns:cliente>
	
	<tns:cliente dni="71391113E">
		<tns:nombre>Fernando Martínez</tns:nombre>
		<tns:email>fmartinez@unican.es</tns:email>
		<tns:seguro id="IJK-123456">
			<tns:tipo>TERCEROS</tns:tipo>
			<tns:vehiculo matricula="3467 KIO">
				<tns:potencia>100</tns:potencia>
				<tns:usoprofesional>true</tns:usoprofesional>
			</tns:vehiculo>
		</tns:seguro>
		<tns:parte>
			<tns:importe>112.0</tns:importe>
			<tns:fecha>2019-02-05+12:14</tns:fecha>
			<tns:seguro>FGH-123456</tns:seguro>
		</tns:parte>
	</tns:cliente>
	
</tns:aseguradora>

=== pma93/ServiciosSoftware/Practica1/segurosdomain/bin/src/main/resources/SegurosDomain.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:aseguradora
	xmlns:tns="http://www.unican.es/ss/SegurosDomain"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.unican.es/ss/SegurosDomain SegurosDomain.xsd ">

	<tns:cliente dni="72391113E">
		<tns:nombre>Fernando Solar</tns:nombre>
		<tns:email>fsolar@unican.es</tns:email>
		<tns:seguro id="ABC-123456">
			<tns:tipo>TERCEROS</tns:tipo>
			<tns:vehiculo matricula="3467 KIO">
				<tns:potencia>100</tns:potencia>
				<tns:usoprofesional>false</tns:usoprofesional>
			</tns:vehiculo>
		</tns:seguro>
		<tns:seguro id="DEF-123456">
			<tns:tipo>TODO_RIESGO</tns:tipo>
			<tns:vehiculo matricula="3461 AZE">
				<tns:potencia>240</tns:potencia>
				<tns:usoprofesional>true</tns:usoprofesional>
			</tns:vehiculo>
		</tns:seguro>
		<tns:seguro id="FGH-123456">
			<tns:tipo>TODO_RIESGO</tns:tipo>
			<tns:vehiculo matricula="3462 PAU">
				<tns:potencia>150</tns:potencia>
				<tns:usoprofesional>false</tns:usoprofesional>
			</tns:vehiculo>
		</tns:seguro>
		<!--Parte erroneo-->
		<tns:parte>
			<tns:importe>112.0</tns:importe>
			<tns:fecha>2019-02-01</tns:fecha>
			<tns:seguroref>IJK-123456</tns:seguroref>
		</tns:parte>
	</tns:cliente>
	
	<tns:cliente dni="72152745P">
		<tns:nombre>Pablo Mart√≠nez</tns:nombre>
		<tns:email>pmartinez@unican.es</tns:email>
		<tns:seguro id="IJK-123456">
			<tns:tipo>TERCEROS</tns:tipo>
			<tns:vehiculo matricula="3467 TIO">
				<tns:potencia>100</tns:potencia>
				<tns:usoprofesional>true</tns:usoprofesional>
			</tns:vehiculo>
		</tns:seguro>
		<tns:parte>
			<tns:importe>115.0</tns:importe>
			<tns:fecha>2019-02-06</tns:fecha>
			<tns:seguroref>IJK-123456</tns:seguroref>
		</tns:parte>
		<!--Parte erroneo-->
		<tns:parte>
			<tns:importe>300.0</tns:importe>
			<tns:fecha>2019-02-17</tns:fecha>
			<tns:seguroref>FGH-123456</tns:seguroref>
		</tns:parte>
	</tns:cliente>
	
</tns:aseguradora>
